export const ADD_COLLECTION = 'ADD_COLLECTION';
export const EDIT_COLLECTION = 'EDIT_COLLECTION';
export const ADD_TO_COLLECTION = 'ADD_TO_COLLECTION';
export const DELETE_COLLECTION = 'DELETE_COLLECTION';
export const DELETE_BOOK_FROM_COLLECTION = 'DELETE_BOOK_FROM_COLLECTION';
export const MOVE_BOOK_FROM_COLLECTION = 'MOVE_BOOK_FROM_COLLECTION';